apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tictactoe
  description: A simple TicTacToe game application developed by Musquan.
  annotations:
    github.com/project-slug: Musquan/TicTacToe
    jira/project-key: SCRUM
    jira/label: backstage-component:tictactoe
spec:
  type: application
  owner: ICS
  lifecycle: experimental